coverage:
  status:
    project:
      default:
        target: 60%

ignore:
  - "SourcePackages/**"
  - "DerivedData/**"
  - "Pods/**"
  - "**Tests/**"
  - "**UITests/**"
  - ".build/**"
  - "**/Moya/**"
  - "**/Alamofire/**"
  - "**/SnapKit/**"
  - "**/RealmSwift/**"
  - "**/Realm/**"
  - "**/Kingfisher/**"
  - "**/Firebase/**"
  - "**/GoogleUtilities/**"
  - "**/nanopb/**"
  - "**/gRPC/**"
  - "**/GTMSessionFetcher/**"
  - "**/AppCheck/**"
  - "**/GoogleAppMeasurement/**"
  - "**/Promises/**"
  - "**/abseil/**"
  - "**/leveldb/**"
